---
name: Build

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 12 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t aspera-client .
      - name: Test
        run: docker run --rm aspera-client idr0001 md5sum.txt /tmp/idr0001/